global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "pf-exporter"
    static_configs:
      - targets: ["localhost:2112"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
